# Generated by Django 4.0 on 2021-12-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuzas_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='product',
            field=models.ManyToManyField(through='zuzas_store.BucketProduct', to='zuzas_store.Product'),
        ),
    ]
