# Generated by Django 4.0 on 2021-12-30 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zuzas_store', '0002_bucket_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zuzas_store.product'),
        ),
    ]
