# Generated by Django 4.0 on 2022-01-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zuzas_store', '0003_alter_images_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bucketproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='zuzas_store.product'),
        ),
    ]
