# Generated by Django 4.0 on 2022-01-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zuzas_store', '0004_bucket_total_price_alter_bucketproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bucket', to='zuzas_store.userprofile'),
        ),
    ]
