# Generated by Django 4.0 on 2022-01-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zuzas_store', '0005_alter_bucket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketproduct',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='bucketproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
        migrations.DeleteModel(
            name='BucketProduct',
        ),
    ]
