# Generated by Django 4.0 on 2022-01-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zuzas_store', '0006_remove_bucketproduct_bucket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CartOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cart_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zuzas_store.cartorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zuzas_store.product')),
            ],
        ),
        migrations.AddField(
            model_name='cartorder',
            name='product',
            field=models.ManyToManyField(through='zuzas_store.CartOrderProduct', to='zuzas_store.Product'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bucket', to='zuzas_store.userprofile'),
        ),
    ]
