# Generated by Django 4.0 on 2022-01-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zuzas_store', '0007_cartorder_cartorderproduct_cartorder_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_order', to='zuzas_store.userprofile'),
        ),
        migrations.AlterField(
            model_name='cartorderproduct',
            name='cart_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='zuzas_store.cartorder'),
        ),
        migrations.AlterField(
            model_name='cartorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='zuzas_store.product'),
        ),
    ]
