# Generated by Django 4.0 on 2022-01-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuzas_store', '0008_alter_cartorder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartorderproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
